from PIL import Image, ImageDraw, ImageFont
from datetime import datetime

def add_watermark(img: Image.Image, text: str = "Generated by AI", opacity=128):
    wm = Image.new("RGBA", img.size, (0,0,0,0))
    draw = ImageDraw.Draw(wm)
    font = ImageFont.load_default()
    stamp = f"{text} • {datetime.utcnow().isoformat()[:19]}Z"
    w, h = draw.textlength(stamp, font=font), 12
    # Bottom-right
    x = img.width - w - 10
    y = img.height - h - 10
    draw.text((x, y), stamp, font=font, fill=(255,255,255,opacity))
    return Image.alpha_composite(img.convert("RGBA"), wm).convert("RGB")